name: ci

on:
  push:
    branches:
      - '*'
    tags-ignore:
      - '*'
  pull_request:
    branches:
      - '*'
    tags-ignore:
      - '*'

env:
  CI_SKIP: false

jobs:
  test:
    if: "!contains(github.event.head_commit.message, '[ci skip]') && !contains(github.event.head_commit.message, 'doc:')"
    name: ${{ matrix.os }} ${{ matrix.target }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-18.04]
        target: [13.x]
    timeout-minutes: 120

    steps:
      - name: Git log
        run: |
          if [ -n "$(git describe --exact-match HEAD)" ] && [ -n "$(git log --format=%B -n 1 | grep -iE '^[0-9]+[.]{1,}[0-9]+[.]{1,}[0-9]+')" ]; then
            echo '::set-env name=CI_SKIP::true'
          fi

      - name: Checkout
        if: "env.CI_SKIP == 'false'"
        uses: actions/checkout@v2

      - name: Setup node@${{ matrix.target }}
        if: "env.CI_SKIP == 'false'"
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.target }}

      - name: List versions
        if: "env.CI_SKIP == 'false'"
        continue-on-error: true
        run: |
          node -v && npm version && which npm && pwd && npx envinfo
          echo env.

      - name: Install dependencies
        if: "env.CI_SKIP == 'false'"
        run: |
          npm ci --quiet && npm i web-component-tester

      - name: Lint
        if: "env.CI_SKIP == 'false'"
        run: |
          npm run lint

      - name: Build
        if: "env.CI_SKIP == 'false'"
        run: |
          npm run ts

      - name: Check build
        if: "env.CI_SKIP == 'false'"
        shell: bash
        run: |
          pwd && ls -la

      - name: Run Test
        if: "env.CI_SKIP == 'false'"
        run: |
          npm run test:ci
